import Navbar from '@/components/navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import { Grid } from '@mui/material'
import Searchbar from '@/components/searchbar'
import Logo from '@/components/logo'
import Footer from '@/components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en' className='bg-[#252525] text-[#F0F5F5] flex justify-center'>
      <body className={`${inter.className} w-[90%] py-6`}>
        <div className='grid grid-cols-24 pb-2'>
          <div className=' col-[1_/_span_5] pr-2'>
            <Logo />
          </div>
          <div className='col-[6_/_span_24] pl-2'>
            <Searchbar />
          </div>
        </div>
        <div className='grid grid-cols-24 py-2'>
          <div className=' col-[1_/_span_5] pr-2'>
            <Navbar />
          </div>
          <div className='col-[6_/_span_24] pl-2'>
            {children}
          </div>
        </div>
        <div className='flex w-full pt-2'>
          <Footer />
        </div>
      </body>
    </html>
  )
}
